CREATE DATABASE IF NOT EXISTS homeops CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE homeops;

CREATE TABLE IF NOT EXISTS meta_schema_version (
  id INT PRIMARY KEY AUTO_INCREMENT,
  version VARCHAR(32) NOT NULL,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
